module.exports = {
    login: "dandres10",
    id: 16737679,
    node_id: "MDQ6VXNlcjE2NzM3Njc5",
    avatar_url: "https://avatars.githubusercontent.com/u/16737679?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dandres10",
    html_url: "https://github.com/dandres10",
    followers_url: "https://api.github.com/users/dandres10/followers",
    following_url: "https://api.github.com/users/dandres10/following{/other_user}",
    gists_url: "https://api.github.com/users/dandres10/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dandres10/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dandres10/subscriptions",
    organizations_url: "https://api.github.com/users/dandres10/orgs",
    repos_url: "https://api.github.com/users/dandres10/repos",
    events_url: "https://api.github.com/users/dandres10/events{/privacy}",
    received_events_url: "https://api.github.com/users/dandres10/received_events",
    type: "User",
    site_admin: false,
    name: null,
    company: "DigitalWare",
    blog: "",
    location: "Bogotá - Colombia",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: "dandresleon64",
    public_repos: 17,
    public_gists: 1,
    followers: 1,
    following: 0,
    created_at: "2016-01-16T21:17:16Z",
    updated_at: "2022-09-16T14:00:08Z"
}